# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vone', '0002_auto_20180416_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
    ]
